[project]
name = "yaht"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "vulture>=2.14",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
